import type jsPDF from 'jspdf';
import { BRAND, hexToRgb } from '../brand';
import { drawBrandMark } from './backgroundArt';
import { setPdfFont } from './pdfFonts';
import { PAGE, TYPE } from './tokens';

export function drawRunningChrome(
  doc: jsPDF,
  displayPage: number,
  displayTotal: number,
  opts: { sectionLabel?: string },
) {
  const [nR, nG, nB] = hexToRgb(BRAND.NAVY);
  const [aR, aG, aB] = hexToRgb(BRAND.ACCENT);
  const [cR, cG, cB] = hexToRgb(BRAND.CREAM_DARK);
  const [mR, mG, mB] = hexToRgb(BRAND.MUTED);

  drawBrandMark(doc, PAGE.w - PAGE.marginX - 10, 5.5, 10);

  setPdfFont(doc, 'helvetica', 'bold');
  doc.setFontSize(TYPE.chrome);
  doc.setTextColor(mR, mG, mB);
  doc.text(`${BRAND.product.toUpperCase()} · ${BRAND.ORG_SHORT.toUpperCase()}`, PAGE.marginX, PAGE.headerY, { charSpace: 0.3 });

  if (opts.sectionLabel) {
    setPdfFont(doc, 'helvetica', 'bold');
    doc.setFontSize(TYPE.chrome);
    doc.setTextColor(nR, nG, nB);
    const label = opts.sectionLabel.length > 40 ? `${opts.sectionLabel.slice(0, 37)}…` : opts.sectionLabel;
    doc.text(label, PAGE.w / 2 + 8, PAGE.headerY);
  }

  doc.setFillColor(cR, cG, cB);
  doc.rect(PAGE.marginX, PAGE.headerRuleY, PAGE.contentW, 0.35, 'F');
  doc.setFillColor(aR, aG, aB);
  doc.rect(PAGE.marginX, PAGE.headerRuleY, 16, 0.35, 'F');

  doc.setFillColor(cR, cG, cB);
  doc.rect(PAGE.marginX, PAGE.h - 11, PAGE.contentW, 0.35, 'F');
  doc.setFillColor(aR, aG, aB);
  doc.rect(PAGE.marginX, PAGE.h - 11, 16, 0.35, 'F');

  setPdfFont(doc, 'helvetica', 'normal');
  doc.setFontSize(TYPE.chrome);
  doc.setTextColor(mR, mG, mB);
  doc.text(`Generated by ${BRAND.product} · Confidential`, PAGE.marginX, PAGE.footerY);
  doc.text(`Page ${displayPage} of ${displayTotal}`, PAGE.w - PAGE.marginX, PAGE.footerY, { align: 'right' });
}

export function drawSectionMasthead(
  doc: jsPDF,
  y: number,
  fonts: { serif: string; sans: string },
  sectionNo: number,
  title: string,
): number {
  const [nR, nG, nB] = hexToRgb(BRAND.NAVY);
  const [aR, aG, aB] = hexToRgb(BRAND.ACCENT);
  const barH = 16;
  doc.setFillColor(nR, nG, nB);
  doc.rect(0, y, PAGE.w, barH, 'F');
  doc.setFillColor(aR, aG, aB);
  doc.rect(0, y + barH - 0.8, PAGE.w, 0.8, 'F');

  setPdfFont(doc, fonts.sans, 'bold');
  doc.setFontSize(7);
  doc.setTextColor(aR, aG, aB);
  doc.text(`SECTION ${sectionNo}`, PAGE.marginX, y + 6, { charSpace: 0.5 });

  setPdfFont(doc, fonts.serif, 'bold');
  doc.setFontSize(TYPE.masthead);
  doc.setTextColor(255, 255, 255);
  const lines = doc.splitTextToSize(title, PAGE.contentW);
  doc.text(lines[0], PAGE.marginX, y + 12.5);

  const next = y + barH + 6;
  doc.setFillColor(aR, aG, aB);
  doc.rect(PAGE.marginX, next, 16, 0.7, 'F');
  return next + 5;
}
