import type jsPDF from 'jspdf';
import { BRAND, formatLongDate, hexToRgb } from '../brand';
import { drawBrandMark, drawCoverArt, fillWarmPage } from './backgroundArt';
import { setPdfFont } from './pdfFonts';
import { PAGE, TYPE } from './tokens';

function rgb(hex: string) {
  return hexToRgb(hex);
}

export function drawCover(
  doc: jsPDF,
  fonts: { serif: string; sans: string; mono: string },
  opts: {
    title: string;
    subtitle?: string;
    participants: number;
    durationSeconds: number;
    recordedAt?: string;
    modelVersion?: string;
  },
) {
  fillWarmPage(doc);
  drawCoverArt(doc);

  drawBrandMark(doc, PAGE.marginX, 42, 14);
  const [nR, nG, nB] = rgb(BRAND.NAVY);
  const [aR, aG, aB] = rgb(BRAND.ACCENT);
  const [mR, mG, mB] = rgb(BRAND.MUTED);

  setPdfFont(doc, fonts.sans, 'bold');
  doc.setFontSize(11);
  doc.setTextColor(nR, nG, nB);
  doc.text(BRAND.lockup.toUpperCase(), PAGE.marginX + 17, 50);

  doc.setFillColor(nR, nG, nB);
  doc.rect(PAGE.marginX, 62, 16, 1.1, 'F');
  doc.setFillColor(aR, aG, aB);
  doc.rect(PAGE.marginX + 17, 62, 9, 1.1, 'F');

  setPdfFont(doc, fonts.sans, 'bold');
  doc.setFontSize(TYPE.eyebrow);
  doc.setTextColor(nR, nG, nB);
  doc.text('TRANSCRIPT · STUDIO', PAGE.marginX, 78, { charSpace: 0.5 });

  setPdfFont(doc, fonts.serif, 'bold');
  doc.setFontSize(TYPE.coverTitle);
  doc.setTextColor(nR, nG, nB);
  const titleLines = doc.splitTextToSize(opts.title, PAGE.contentW * 0.72);
  doc.text(titleLines.slice(0, 3), PAGE.marginX, 96);

  const hh = Math.floor(opts.durationSeconds / 3600);
  const mm = Math.floor((opts.durationSeconds % 3600) / 60);
  const ss = Math.floor(opts.durationSeconds % 60);
  const clock = `${String(hh).padStart(2, '0')}:${String(mm).padStart(2, '0')}:${String(ss).padStart(2, '0')}`;
  const recorded = opts.recordedAt ? formatLongDate(new Date(opts.recordedAt)) : formatLongDate();
  const sub = opts.subtitle
    ?? `${opts.participants} participant${opts.participants === 1 ? '' : 's'}  ·  ${clock}  ·  recorded ${recorded}`;

  setPdfFont(doc, fonts.sans, 'normal');
  doc.setFontSize(10);
  doc.setTextColor(mR, mG, mB);
  doc.text(doc.splitTextToSize(sub, PAGE.contentW * 0.8), PAGE.marginX, 96 + titleLines.slice(0, 3).length * 11 + 8);

  const bandY = PAGE.h - 40;
  doc.setFillColor(nR, nG, nB);
  doc.rect(PAGE.marginX, bandY, PAGE.contentW, 0.45, 'F');
  doc.setFillColor(aR, aG, aB);
  doc.rect(PAGE.marginX, bandY, 9, 0.45, 'F');

  setPdfFont(doc, fonts.mono, 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(mR, mG, mB);
  const model = opts.modelVersion ? `  ·  ${opts.modelVersion}` : '';
  doc.text(`Generated by ${BRAND.product}  ·  ${formatLongDate()}${model}`, PAGE.marginX, bandY + 8);

  setPdfFont(doc, fonts.sans, 'bold');
  doc.setFontSize(7.5);
  doc.setTextColor(nR, nG, nB);
  doc.text('CONFIDENTIAL', PAGE.w - PAGE.marginX, bandY + 8, { align: 'right' });

  setPdfFont(doc, fonts.sans, 'normal');
  doc.setFontSize(8);
  doc.setTextColor(mR, mG, mB);
  doc.text(BRAND.ORG_FULL, PAGE.marginX, bandY + 16);
}

export async function drawBackCover(
  doc: jsPDF,
  fonts: { serif: string; sans: string },
) {
  doc.addPage();
  const [nR, nG, nB] = rgb(BRAND.NAVY);
  const [aR, aG, aB] = rgb(BRAND.ACCENT);
  doc.setFillColor(nR, nG, nB);
  doc.rect(0, 0, PAGE.w, PAGE.h, 'F');
  doc.setFillColor(aR, aG, aB);
  doc.rect(0, 0, 6, PAGE.h, 'F');

  drawBrandMark(doc, PAGE.marginX, PAGE.h / 2 - 28, 18);
  setPdfFont(doc, fonts.serif, 'bold');
  doc.setFontSize(22);
  doc.setTextColor(255, 255, 255);
  doc.text(BRAND.lockup, PAGE.marginX, PAGE.h / 2 + 4);

  setPdfFont(doc, fonts.sans, 'normal');
  doc.setFontSize(10);
  doc.setTextColor(aR, aG, aB);
  doc.text(BRAND.tagline, PAGE.marginX, PAGE.h / 2 + 14);

  setPdfFont(doc, fonts.sans, 'normal');
  doc.setFontSize(8);
  doc.setTextColor(200, 214, 204);
  doc.text(`${BRAND.ORG_FULL}  ·  Confidential`, PAGE.marginX, PAGE.h - 24);
}
